name: dealsmo-backend
services:
  x-backend-base: &backend_base
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    image: dealsmo_backend
    volumes:
      - .:/app:z
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    env_file:
      - ./.envs/.env.local
    expose:
      - "8000"
    networks:
      - dealsmo_nw

  backend:
    <<: *backend_base
    container_name: dealsmo-backend
    depends_on:
      - postgres
      - mailpit
      - redis
      - celeryworker
      - es
    command: ["/wait-for-it.sh", "postgres:5432", "--", "/start"]

  postgres:
    container_name: dealsmo-postgres
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.env.local
    networks:
      - dealsmo_nw

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: dealsmo-es
    platform: linux/amd64  # Use x86 emulation for stability
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Important for DRF to connect without authentication
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - dealsmo_nw

  mailpit:
    image: docker.io/axllent/mailpit:v1.15
    container_name: dealsmo_mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:  
      - dealsmo_mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1  
    networks:
      - dealsmo_nw

  redis:
    image: redis:7.0-alpine3.19
    command: redis-server --appendonly yes
    container_name: dealsmo_redis
    volumes:
      - dealsmo_redis_data:/data
    networks:
      - dealsmo_nw

  celeryworker:
    <<: *backend_base
    image: dealsmo_celeryworker
    container_name: dealsmo_celeryworker
    depends_on:
      - redis
      - postgres
    command: /start-celeryworker

  celerybeat:
    <<: *backend_base
    image: dealsmo_celerybeat
    container_name: dealsmo_celerybeat
    depends_on:
      - redis
      - postgres
    command: /start-celerybeat

  flower:
    <<: *backend_base
    image: dealsmo_flower
    container_name: dealsmo_flower
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celeryworker
    command: /start-flower

  nginx:
    container_name: dealsmo_nginx
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    # restart: always    
    ports:
      - "8080:80"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - logs_store:/var/log/nginx
    depends_on:
      - backend
    networks:
      - dealsmo_nw 

networks:
  dealsmo_nw:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  dealsmo_mailpit_data: {}
  dealsmo_redis_data: {}
  logs_store: {}