# Generated by Django 5.0.2 on 2025-04-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("declined", "Declined"),
                ],
                default="open",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
