#!/bin/bash

set -o errexit

set -o pipefail

set -o nounset

# Debugging line to print environment variables
# env

if [ -z "${POSTGRES_USER}" ]; then
  base_postgres_image_default_user='postgres'
  export POSTGRES_USER="${base_postgres_image_default_user}"
fi

export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

/wait-for-it.sh db:5432 --timeout=30 -- echo "PostgreSQL is available"

exec "$@"