# Generated by Django 5.0.2 on 2025-02-16 19:43

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(
                default="Los Angeles", max_length=180, verbose_name="city"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(
                default="USA", max_length=2, verbose_name="country"
            ),
        ),
    ]
