# Generated by Django 5.0.2 on 2025-03-29 02:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_profile_report_count_profile_reputation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="profile_photo",
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Avatar"
            ),
        ),
    ]
