# Generated by Django 5.0.2 on 2025-03-12 00:41

import core_apps.articles.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_alter_articlecategory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="end_date",
            field=models.DateTimeField(
                default=core_apps.articles.models.get_default_end_date,
                help_text="Date when the article will be archived",
                verbose_name="End Date",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="start_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date when the article becomes visible",
                verbose_name="Start Date",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
